### ISSUE TITLE
リソース設計をする

### ISSUE THREAD

**Issue by 2525nicole** [2525nicole/memo-recall#17]

**Comment by 2525nicole** [comment]
| Methods | Path | Description |
| -- | -- | -- |
GET | /users/sign_in | ログイン画面を表示する
POST | /users/sign_in | ログインする
DELETE | /users/sign_out | ログアウトする
GET | /users/sign_up | アカウント作成画面を表示する
POST | /users | アカウント登録をする
GET | / | トップページ（ランダムの思い出を表示する）
GET | /memories/new | 思い出登録フォームを表示する
POST | /memories | 思い出を登録する
GET | /memories | 思い出の一覧を表示する
GET | /memories/:memory_id/edit | 思い出の編集フォーム
PUT | /memories/:memory_id | 思い出を編集する
GET | /memories/:memory_id/delete_confirmation | 思い出の削除確認モーダル
GET | /memories/:memory_id/delete_completion | 思い出の削除完了モーダル
DELETE | /memories/:memories_id | 思い出を削除する
GET | /categories/new | カテゴリー登録フォーム
POST | /categories | カテゴリーを登録する
GET | /categories/settings | カテゴリー設定ページ（カテゴリー一覧を表示）
GET | /categories/:category_id/edit | カテゴリーの編集モーダル
POST | /categories/:category_id | カテゴリーを編集する
GET | /categories/:category_id/delete_confirmation | カテゴリーの削除確認モーダル
DELETE | /categories/:category_id | カテゴリーを削除する
GET | /categories/:category_id/memories/delete_confirmation | カテゴリーに紐づく削除確認モーダル
DELETE | /categories/:category_id/memories | カテゴリーに紐づく思い出を削除する
GET | /categories/:category_id//memories/delete_completion | カテゴリーに紐づく思い出の削除完了モーダル
GET | /users/password/new | パスワード再設定メールページの表示
POST | /users/password | パスワード再設定メール送信
GET | /users/password/sent | パスワード再設定メール送信完了画面の表示
GET | /users/password/edit | パスワード再設定画面の表示
GET | /users/settings | アカウント設定変更ページの表示
PUT | /users | アカウント情報を変更する
GET | /users/:user_id/delete_confirmation | 退会確認のモーダル
DELETE | /users/:user_id | 退会する
GET | /privacy | プライバシーポリシーページを表示する
GET | /terms | 利用規約ページを表示する
GET | /guides | サービスガイドを表示する

**Comment by maedana** [comment]
> GET	/categories/settings	カテゴリー設定ページを表示する（カテゴリー一覧を表示）

単に`GET /categories` にしなかったのはなにか理由があるのでしょうか?

**Comment by 2525nicole** [comment]
@maedana 
ご確認ありがとうございます🙇‍♀️
記述の仕方がわかりづらく申し訳ありません！

以下のように「カテゴリーの一覧を表示する」というよりも、
**「カテゴリーの設定（新規追加、編集、削除）を行う」目的がメイン**のページを想定しているため`GET /categories/settings`にいたしました🙏

<img width="364" alt="image" src="https://github.com/2525nicole/memo-recall/assets/104631303/2478bf19-cf23-4fab-89ca-bc7e2e9ab85a">

**Comment by maedana** [comment]
なるほどー、しかしメインで表示するものはあくまでもカテゴリ一覧だと思いますし、これくらいなら`categoriesでいいのかなーと思いました。最終的にはどちらでもいいと思います。

**Comment by 2525nicole** [comment]
@maedana 
早速のご確認ありがとうございます！
またご意見もいただき勉強になります🙇‍♀️
頂戴したご意見も踏まえ、簡潔なほうがよいと感じたので`categories`にしようと思います！

【メモ】以下で進める

| Methods | Path | Description |
| -- | -- | -- |
GET | /users/sign_in | ログイン画面を表示する
POST | /users/sign_in | ログインする
DELETE | /users/sign_out | ログアウトする
GET | /users/sign_up | アカウント作成画面を表示する
POST | /users | アカウント登録をする
GET | / | トップページ（ランダムの思い出を表示する）
GET | /memories/new | 思い出登録フォームを表示する
POST | /memories | 思い出を登録する
GET | /memories | 思い出の一覧を表示する
GET | /memories/:memory_id/edit | 思い出の編集フォームを表示する
PUT | /memories/:memory_id | 思い出を編集する
GET | /memories/:memory_id/delete_confirmation | 思い出の削除確認モーダルを表示する
GET | /memories/:memory_id/delete_completion | 思い出の削除完了モーダルを表示する
DELETE | /memories/:memory_id | 思い出を削除する
GET | /categories/new | カテゴリー登録フォームを表示する
POST | /categories | カテゴリーを登録する
GET | /categories | カテゴリー設定ページを表示する（カテゴリー一覧を表示する）
GET | /categories/:category_id/edit | カテゴリーの編集モーダルを表示する
PUT | /categories/:category_id | カテゴリーを編集する
GET | /categories/:category_id/delete_confirmation | カテゴリーの削除確認モーダルを表示する
DELETE | /categories/:category_id | カテゴリーを削除する
GET | /categories/:category_id/memories/delete_confirmation | カテゴリーと、紐づく削除確認モーダルを表示する
DELETE | /categories/:category_id/memories | カテゴリーと、紐づく思い出を削除する
GET | /categories/:category_id/memories/delete_completion | カテゴリーと、紐づく思い出の削除完了モーダルを表示する
GET | /users/password/new | パスワード再設定メールページを表示する
POST | /users/password | パスワード再設定メールを送信する
GET | /users/password/sent | パスワード再設定メール送信完了画面を表示する
GET | /users/password/edit | パスワード再設定画面を表示する
GET | /users/settings | アカウント設定変更ページを表示する
PUT | /users/:user_id | アカウント情報を変更する
GET | /users/:user_id/delete_confirmation | 退会確認のモーダルを表示する
DELETE | /users/:user_id | 退会する
GET | /privacy | プライバシーポリシーページを表示する
GET | /terms | 利用規約ページを表示する
GET | /guides | サービスガイドを表示する

**Comment by 2525nicole** [comment]
確認OKをいただいたため、クローズします🙏
