### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by 2525nicole** [2525nicole/memo-recall#4]

**Comment by 2525nicole** [comment]
![Image](https://github.com/2525nicole/memo-recall/assets/104631303/333472f4-b2c7-4e64-ac52-d1445cda8714)

**Comment by maedana** [comment]
- Memoriesのmemoty_contentはテーブルがMemoriesなので`memory_`が重複して冗長かなーと思います。
- Categoriesのcategory_nameも同上ですね
- Usersテーブルはemail以外にも属性あるかと思いますが、あえて省略してるのでしょうか(パスワード等)

**Comment by maedana** [comment]
> はい、ログイン機能はdeviseで実装する予定のため省略していました！
> 同じくログイン機能で使用するpasseordも記載したほうが親切だと感じたので追記しました🙏

なるほど、了解です。なお細かいですが、`password`というカラムは追加されません。これだと平文でパスワード保存するように見えますけど、実際は暗号化された値が入りますしカラム名も違いますね。

**Comment by 2525nicole** [comment]
@maedana 
>passwordというカラムは追加されません。これだと平文でパスワード保存するように見えますけど、実際は暗号化された値が入りますしカラム名も違いますね。

実際は`encrypted_password`ですね🙇‍♀️
こちらも早速のご確認とコメントありがとうございました！

【メモ】正しいカラム名を反映
<img width="710" alt="image" src="https://github.com/2525nicole/memo-recall/assets/104631303/c9c78495-23e5-4c68-87f7-c33f3794368e">

**Comment by 2525nicole** [comment]
確認OKをいただいたため、クローズします🙏
